version: "3"
services:
#React app
  frontend:
    image: earthzphanu/frontend:latest
    restart: on-failure
    container_name: frontend
    links:
      - article
      - api-gateway
      - matching
    ports:
      - '3000:3000'
    #environment:
      #WAIT_HOSTS: article:8000, api-gateway:5000
      #WAIT_HOSTS_TIMEOUT: 120
#Article Service
  article:
    # build: ./service/article-service
    # image: article_service
    image: earthzphanu/article_service:latest
    restart: on-failure
    container_name: article
    links:
      - mongo
      - eureka
      - circuit-breaker
    depends_on:
      - mongo
      - eureka
    environment:
      WAIT_HOSTS: mongo:27017, eureka:8761, matching:5050
      WAIT_HOSTS_TIMEOUT: 120
      MONGODB_URL: 'mongodb://mongo:27017/Article-service'
      EUREKA_CLIENT_HOST: 'article'
      EUREKA_CLIENT_URL: 'http://article:'
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8761
    ports:
      - '8000:8000'

#Matching Service
  matching:
    container_name: matching
    image: earthzphanu/matching_service:latest
    restart: on-failure
    links:
      - mongo
      - eureka
      - circuit-breaker
    depends_on:
      - mongo
      - eureka
    environment:
      WAIT_HOSTS: mongo:27017, eureka:8761
      WAIT_HOSTS_TIMEOUT: 120
      MONGODB_URL: 'mongodb://mongo:27017/subject'
      EUREKA_CLIENT_HOST: 'matching'
      EUREKA_CLIENT_URL: 'http://matching:'
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8761
    ports:
      - '5050:5050'

#Database
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/mongo
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data:/data/mongo
    ports: 
      - '27017:27017'

#APIGateway
  api-gateway:
    container_name: api-gateway
    image: earthzphanu/api_gateway
    restart: on-failure
    links:
      - eureka
    depends_on:
      - eureka
      - article
      - matching
    environment:
      WAIT_HOSTS: eureka:8761, article:8000, matching:5050
      WAIT_HOSTS_TIMEOUT: 120
      EUREKA_CLIENT_HOST: 'api-gateway'
      EUREKA_CLIENT_URL: 'http://api-gateway:'
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8761
    ports:
      - '5000:5000'
#Service Discovery
  eureka:
    container_name: eureka
    image: springcloud/eureka
    ports:
      - '8761:8761'
# Circuit Breaker
  circuit-breaker:
    container_name: circuit-breaker
    image: earthzphanu/circuit_breaker
    ports:
      - '8888:8888'
