version: 2
jobs:
    #Article Service
    article:
        working_directory: ~/SOA2019_Group12/service/article-service
        docker:
            - image: circleci/node:12.0.0-alpine
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
            - checkout:
                path: ~SOA2019_Group12/service
            - run:
                name: Build Article service's Image
                command: |
                    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                    docer build -t $DOCKER_USERNAME/article_service .
                    docker push $DOCKER_USERNAME/article_service

workflows:
    version: 2
    compile:
        jobs:
            - article:
                filters:
                    branches:
                        only:
                            master
